// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: app/userratelimit/command/command.proto

package command

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserRateLimitService_SetUserRateLimit_FullMethodName    = "/xray.app.userratelimit.command.UserRateLimitService/SetUserRateLimit"
	UserRateLimitService_RemoveUserRateLimit_FullMethodName = "/xray.app.userratelimit.command.UserRateLimitService/RemoveUserRateLimit"
	UserRateLimitService_GetUserRateLimit_FullMethodName    = "/xray.app.userratelimit.command.UserRateLimitService/GetUserRateLimit"
	UserRateLimitService_ListUserRateLimits_FullMethodName  = "/xray.app.userratelimit.command.UserRateLimitService/ListUserRateLimits"
)

// UserRateLimitServiceClient is the client API for UserRateLimitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserRateLimitServiceClient interface {
	SetUserRateLimit(ctx context.Context, in *SetUserRateLimitRequest, opts ...grpc.CallOption) (*SetUserRateLimitResponse, error)
	RemoveUserRateLimit(ctx context.Context, in *RemoveUserRateLimitRequest, opts ...grpc.CallOption) (*RemoveUserRateLimitResponse, error)
	GetUserRateLimit(ctx context.Context, in *GetUserRateLimitRequest, opts ...grpc.CallOption) (*GetUserRateLimitResponse, error)
	ListUserRateLimits(ctx context.Context, in *ListUserRateLimitsRequest, opts ...grpc.CallOption) (*ListUserRateLimitsResponse, error)
}

type userRateLimitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRateLimitServiceClient(cc grpc.ClientConnInterface) UserRateLimitServiceClient {
	return &userRateLimitServiceClient{cc}
}

func (c *userRateLimitServiceClient) SetUserRateLimit(ctx context.Context, in *SetUserRateLimitRequest, opts ...grpc.CallOption) (*SetUserRateLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserRateLimitResponse)
	err := c.cc.Invoke(ctx, UserRateLimitService_SetUserRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRateLimitServiceClient) RemoveUserRateLimit(ctx context.Context, in *RemoveUserRateLimitRequest, opts ...grpc.CallOption) (*RemoveUserRateLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveUserRateLimitResponse)
	err := c.cc.Invoke(ctx, UserRateLimitService_RemoveUserRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRateLimitServiceClient) GetUserRateLimit(ctx context.Context, in *GetUserRateLimitRequest, opts ...grpc.CallOption) (*GetUserRateLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRateLimitResponse)
	err := c.cc.Invoke(ctx, UserRateLimitService_GetUserRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRateLimitServiceClient) ListUserRateLimits(ctx context.Context, in *ListUserRateLimitsRequest, opts ...grpc.CallOption) (*ListUserRateLimitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserRateLimitsResponse)
	err := c.cc.Invoke(ctx, UserRateLimitService_ListUserRateLimits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRateLimitServiceServer is the server API for UserRateLimitService service.
// All implementations must embed UnimplementedUserRateLimitServiceServer
// for forward compatibility.
type UserRateLimitServiceServer interface {
	SetUserRateLimit(context.Context, *SetUserRateLimitRequest) (*SetUserRateLimitResponse, error)
	RemoveUserRateLimit(context.Context, *RemoveUserRateLimitRequest) (*RemoveUserRateLimitResponse, error)
	GetUserRateLimit(context.Context, *GetUserRateLimitRequest) (*GetUserRateLimitResponse, error)
	ListUserRateLimits(context.Context, *ListUserRateLimitsRequest) (*ListUserRateLimitsResponse, error)
	mustEmbedUnimplementedUserRateLimitServiceServer()
}

// UnimplementedUserRateLimitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserRateLimitServiceServer struct{}

func (UnimplementedUserRateLimitServiceServer) SetUserRateLimit(context.Context, *SetUserRateLimitRequest) (*SetUserRateLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUserRateLimit not implemented")
}
func (UnimplementedUserRateLimitServiceServer) RemoveUserRateLimit(context.Context, *RemoveUserRateLimitRequest) (*RemoveUserRateLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUserRateLimit not implemented")
}
func (UnimplementedUserRateLimitServiceServer) GetUserRateLimit(context.Context, *GetUserRateLimitRequest) (*GetUserRateLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserRateLimit not implemented")
}
func (UnimplementedUserRateLimitServiceServer) ListUserRateLimits(context.Context, *ListUserRateLimitsRequest) (*ListUserRateLimitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserRateLimits not implemented")
}
func (UnimplementedUserRateLimitServiceServer) mustEmbedUnimplementedUserRateLimitServiceServer() {}
func (UnimplementedUserRateLimitServiceServer) testEmbeddedByValue()                              {}

// UnsafeUserRateLimitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRateLimitServiceServer will
// result in compilation errors.
type UnsafeUserRateLimitServiceServer interface {
	mustEmbedUnimplementedUserRateLimitServiceServer()
}

func RegisterUserRateLimitServiceServer(s grpc.ServiceRegistrar, srv UserRateLimitServiceServer) {
	// If the following call panics, it indicates UnimplementedUserRateLimitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserRateLimitService_ServiceDesc, srv)
}

func _UserRateLimitService_SetUserRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRateLimitServiceServer).SetUserRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRateLimitService_SetUserRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRateLimitServiceServer).SetUserRateLimit(ctx, req.(*SetUserRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRateLimitService_RemoveUserRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRateLimitServiceServer).RemoveUserRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRateLimitService_RemoveUserRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRateLimitServiceServer).RemoveUserRateLimit(ctx, req.(*RemoveUserRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRateLimitService_GetUserRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRateLimitServiceServer).GetUserRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRateLimitService_GetUserRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRateLimitServiceServer).GetUserRateLimit(ctx, req.(*GetUserRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRateLimitService_ListUserRateLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRateLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRateLimitServiceServer).ListUserRateLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRateLimitService_ListUserRateLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRateLimitServiceServer).ListUserRateLimits(ctx, req.(*ListUserRateLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRateLimitService_ServiceDesc is the grpc.ServiceDesc for UserRateLimitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRateLimitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xray.app.userratelimit.command.UserRateLimitService",
	HandlerType: (*UserRateLimitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetUserRateLimit",
			Handler:    _UserRateLimitService_SetUserRateLimit_Handler,
		},
		{
			MethodName: "RemoveUserRateLimit",
			Handler:    _UserRateLimitService_RemoveUserRateLimit_Handler,
		},
		{
			MethodName: "GetUserRateLimit",
			Handler:    _UserRateLimitService_GetUserRateLimit_Handler,
		},
		{
			MethodName: "ListUserRateLimits",
			Handler:    _UserRateLimitService_ListUserRateLimits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/userratelimit/command/command.proto",
}
