// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: app/userratelimit/command/command.proto

package command

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetUserRateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	UplinkBps     int64                  `protobuf:"varint,2,opt,name=uplink_bps,json=uplinkBps,proto3" json:"uplink_bps,omitempty"`
	DownlinkBps   int64                  `protobuf:"varint,3,opt,name=downlink_bps,json=downlinkBps,proto3" json:"downlink_bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserRateLimitRequest) Reset() {
	*x = SetUserRateLimitRequest{}
	mi := &file_app_userratelimit_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserRateLimitRequest) ProtoMessage() {}

func (x *SetUserRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_userratelimit_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserRateLimitRequest.ProtoReflect.Descriptor instead.
func (*SetUserRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_app_userratelimit_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *SetUserRateLimitRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SetUserRateLimitRequest) GetUplinkBps() int64 {
	if x != nil {
		return x.UplinkBps
	}
	return 0
}

func (x *SetUserRateLimitRequest) GetDownlinkBps() int64 {
	if x != nil {
		return x.DownlinkBps
	}
	return 0
}

type SetUserRateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserRateLimitResponse) Reset() {
	*x = SetUserRateLimitResponse{}
	mi := &file_app_userratelimit_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserRateLimitResponse) ProtoMessage() {}

func (x *SetUserRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_userratelimit_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserRateLimitResponse.ProtoReflect.Descriptor instead.
func (*SetUserRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_app_userratelimit_command_command_proto_rawDescGZIP(), []int{1}
}

type RemoveUserRateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRateLimitRequest) Reset() {
	*x = RemoveUserRateLimitRequest{}
	mi := &file_app_userratelimit_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRateLimitRequest) ProtoMessage() {}

func (x *RemoveUserRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_userratelimit_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRateLimitRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_app_userratelimit_command_command_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveUserRateLimitRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RemoveUserRateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRateLimitResponse) Reset() {
	*x = RemoveUserRateLimitResponse{}
	mi := &file_app_userratelimit_command_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRateLimitResponse) ProtoMessage() {}

func (x *RemoveUserRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_userratelimit_command_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRateLimitResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_app_userratelimit_command_command_proto_rawDescGZIP(), []int{3}
}

type GetUserRateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRateLimitRequest) Reset() {
	*x = GetUserRateLimitRequest{}
	mi := &file_app_userratelimit_command_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRateLimitRequest) ProtoMessage() {}

func (x *GetUserRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_userratelimit_command_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRateLimitRequest.ProtoReflect.Descriptor instead.
func (*GetUserRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_app_userratelimit_command_command_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRateLimitRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserRateLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	UplinkBps     int64                  `protobuf:"varint,2,opt,name=uplink_bps,json=uplinkBps,proto3" json:"uplink_bps,omitempty"`
	DownlinkBps   int64                  `protobuf:"varint,3,opt,name=downlink_bps,json=downlinkBps,proto3" json:"downlink_bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRateLimitResponse) Reset() {
	*x = GetUserRateLimitResponse{}
	mi := &file_app_userratelimit_command_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRateLimitResponse) ProtoMessage() {}

func (x *GetUserRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_userratelimit_command_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRateLimitResponse.ProtoReflect.Descriptor instead.
func (*GetUserRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_app_userratelimit_command_command_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRateLimitResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetUserRateLimitResponse) GetUplinkBps() int64 {
	if x != nil {
		return x.UplinkBps
	}
	return 0
}

func (x *GetUserRateLimitResponse) GetDownlinkBps() int64 {
	if x != nil {
		return x.DownlinkBps
	}
	return 0
}

type UserRateLimitItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	UplinkBps     int64                  `protobuf:"varint,2,opt,name=uplink_bps,json=uplinkBps,proto3" json:"uplink_bps,omitempty"`
	DownlinkBps   int64                  `protobuf:"varint,3,opt,name=downlink_bps,json=downlinkBps,proto3" json:"downlink_bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRateLimitItem) Reset() {
	*x = UserRateLimitItem{}
	mi := &file_app_userratelimit_command_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRateLimitItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRateLimitItem) ProtoMessage() {}

func (x *UserRateLimitItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_userratelimit_command_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRateLimitItem.ProtoReflect.Descriptor instead.
func (*UserRateLimitItem) Descriptor() ([]byte, []int) {
	return file_app_userratelimit_command_command_proto_rawDescGZIP(), []int{6}
}

func (x *UserRateLimitItem) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRateLimitItem) GetUplinkBps() int64 {
	if x != nil {
		return x.UplinkBps
	}
	return 0
}

func (x *UserRateLimitItem) GetDownlinkBps() int64 {
	if x != nil {
		return x.DownlinkBps
	}
	return 0
}

type ListUserRateLimitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRateLimitsRequest) Reset() {
	*x = ListUserRateLimitsRequest{}
	mi := &file_app_userratelimit_command_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRateLimitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRateLimitsRequest) ProtoMessage() {}

func (x *ListUserRateLimitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_userratelimit_command_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRateLimitsRequest.ProtoReflect.Descriptor instead.
func (*ListUserRateLimitsRequest) Descriptor() ([]byte, []int) {
	return file_app_userratelimit_command_command_proto_rawDescGZIP(), []int{7}
}

type ListUserRateLimitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserRateLimitItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRateLimitsResponse) Reset() {
	*x = ListUserRateLimitsResponse{}
	mi := &file_app_userratelimit_command_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRateLimitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRateLimitsResponse) ProtoMessage() {}

func (x *ListUserRateLimitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_userratelimit_command_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRateLimitsResponse.ProtoReflect.Descriptor instead.
func (*ListUserRateLimitsResponse) Descriptor() ([]byte, []int) {
	return file_app_userratelimit_command_command_proto_rawDescGZIP(), []int{8}
}

func (x *ListUserRateLimitsResponse) GetItems() []*UserRateLimitItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_userratelimit_command_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_userratelimit_command_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_userratelimit_command_command_proto_rawDescGZIP(), []int{9}
}

var File_app_userratelimit_command_command_proto protoreflect.FileDescriptor

const file_app_userratelimit_command_command_proto_rawDesc = "" +
	"\n" +
	"'app/userratelimit/command/command.proto\x12\x1exray.app.userratelimit.command\"q\n" +
	"\x17SetUserRateLimitRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"uplink_bps\x18\x02 \x01(\x03R\tuplinkBps\x12!\n" +
	"\fdownlink_bps\x18\x03 \x01(\x03R\vdownlinkBps\"\x1a\n" +
	"\x18SetUserRateLimitResponse\"2\n" +
	"\x1aRemoveUserRateLimitRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x1d\n" +
	"\x1bRemoveUserRateLimitResponse\"/\n" +
	"\x17GetUserRateLimitRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"t\n" +
	"\x18GetUserRateLimitResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1d\n" +
	"\n" +
	"uplink_bps\x18\x02 \x01(\x03R\tuplinkBps\x12!\n" +
	"\fdownlink_bps\x18\x03 \x01(\x03R\vdownlinkBps\"k\n" +
	"\x11UserRateLimitItem\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"uplink_bps\x18\x02 \x01(\x03R\tuplinkBps\x12!\n" +
	"\fdownlink_bps\x18\x03 \x01(\x03R\vdownlinkBps\"\x1b\n" +
	"\x19ListUserRateLimitsRequest\"e\n" +
	"\x1aListUserRateLimitsResponse\x12G\n" +
	"\x05items\x18\x01 \x03(\v21.xray.app.userratelimit.command.UserRateLimitItemR\x05items\"\b\n" +
	"\x06Config2\xcd\x04\n" +
	"\x14UserRateLimitService\x12\x87\x01\n" +
	"\x10SetUserRateLimit\x127.xray.app.userratelimit.command.SetUserRateLimitRequest\x1a8.xray.app.userratelimit.command.SetUserRateLimitResponse\"\x00\x12\x90\x01\n" +
	"\x13RemoveUserRateLimit\x12:.xray.app.userratelimit.command.RemoveUserRateLimitRequest\x1a;.xray.app.userratelimit.command.RemoveUserRateLimitResponse\"\x00\x12\x87\x01\n" +
	"\x10GetUserRateLimit\x127.xray.app.userratelimit.command.GetUserRateLimitRequest\x1a8.xray.app.userratelimit.command.GetUserRateLimitResponse\"\x00\x12\x8d\x01\n" +
	"\x12ListUserRateLimits\x129.xray.app.userratelimit.command.ListUserRateLimitsRequest\x1a:.xray.app.userratelimit.command.ListUserRateLimitsResponse\"\x00B|\n" +
	"\"com.xray.app.userratelimit.commandP\x01Z3github.com/xtls/xray-core/app/userratelimit/command\xaa\x02\x1eXray.App.UserRateLimit.Commandb\x06proto3"

var (
	file_app_userratelimit_command_command_proto_rawDescOnce sync.Once
	file_app_userratelimit_command_command_proto_rawDescData []byte
)

func file_app_userratelimit_command_command_proto_rawDescGZIP() []byte {
	file_app_userratelimit_command_command_proto_rawDescOnce.Do(func() {
		file_app_userratelimit_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_userratelimit_command_command_proto_rawDesc), len(file_app_userratelimit_command_command_proto_rawDesc)))
	})
	return file_app_userratelimit_command_command_proto_rawDescData
}

var file_app_userratelimit_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_app_userratelimit_command_command_proto_goTypes = []any{
	(*SetUserRateLimitRequest)(nil),     // 0: xray.app.userratelimit.command.SetUserRateLimitRequest
	(*SetUserRateLimitResponse)(nil),    // 1: xray.app.userratelimit.command.SetUserRateLimitResponse
	(*RemoveUserRateLimitRequest)(nil),  // 2: xray.app.userratelimit.command.RemoveUserRateLimitRequest
	(*RemoveUserRateLimitResponse)(nil), // 3: xray.app.userratelimit.command.RemoveUserRateLimitResponse
	(*GetUserRateLimitRequest)(nil),     // 4: xray.app.userratelimit.command.GetUserRateLimitRequest
	(*GetUserRateLimitResponse)(nil),    // 5: xray.app.userratelimit.command.GetUserRateLimitResponse
	(*UserRateLimitItem)(nil),           // 6: xray.app.userratelimit.command.UserRateLimitItem
	(*ListUserRateLimitsRequest)(nil),   // 7: xray.app.userratelimit.command.ListUserRateLimitsRequest
	(*ListUserRateLimitsResponse)(nil),  // 8: xray.app.userratelimit.command.ListUserRateLimitsResponse
	(*Config)(nil),                      // 9: xray.app.userratelimit.command.Config
}
var file_app_userratelimit_command_command_proto_depIdxs = []int32{
	6, // 0: xray.app.userratelimit.command.ListUserRateLimitsResponse.items:type_name -> xray.app.userratelimit.command.UserRateLimitItem
	0, // 1: xray.app.userratelimit.command.UserRateLimitService.SetUserRateLimit:input_type -> xray.app.userratelimit.command.SetUserRateLimitRequest
	2, // 2: xray.app.userratelimit.command.UserRateLimitService.RemoveUserRateLimit:input_type -> xray.app.userratelimit.command.RemoveUserRateLimitRequest
	4, // 3: xray.app.userratelimit.command.UserRateLimitService.GetUserRateLimit:input_type -> xray.app.userratelimit.command.GetUserRateLimitRequest
	7, // 4: xray.app.userratelimit.command.UserRateLimitService.ListUserRateLimits:input_type -> xray.app.userratelimit.command.ListUserRateLimitsRequest
	1, // 5: xray.app.userratelimit.command.UserRateLimitService.SetUserRateLimit:output_type -> xray.app.userratelimit.command.SetUserRateLimitResponse
	3, // 6: xray.app.userratelimit.command.UserRateLimitService.RemoveUserRateLimit:output_type -> xray.app.userratelimit.command.RemoveUserRateLimitResponse
	5, // 7: xray.app.userratelimit.command.UserRateLimitService.GetUserRateLimit:output_type -> xray.app.userratelimit.command.GetUserRateLimitResponse
	8, // 8: xray.app.userratelimit.command.UserRateLimitService.ListUserRateLimits:output_type -> xray.app.userratelimit.command.ListUserRateLimitsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_userratelimit_command_command_proto_init() }
func file_app_userratelimit_command_command_proto_init() {
	if File_app_userratelimit_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_userratelimit_command_command_proto_rawDesc), len(file_app_userratelimit_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_userratelimit_command_command_proto_goTypes,
		DependencyIndexes: file_app_userratelimit_command_command_proto_depIdxs,
		MessageInfos:      file_app_userratelimit_command_command_proto_msgTypes,
	}.Build()
	File_app_userratelimit_command_command_proto = out.File
	file_app_userratelimit_command_command_proto_goTypes = nil
	file_app_userratelimit_command_command_proto_depIdxs = nil
}
